### ISSUE TITLE
Issues with Forgot Password Page

### ISSUE THREAD

**Issue by adarsh-site** [Nandini80/Pill-Share#10]
<img width="947" alt="image" src="https://github.com/Nandini80/Pill-Share/assets/120160355/a5bbc2cf-f6aa-4336-80a7-1fa33f8a1caa">

**Comment by adarsh-site** [comment]
@Nandini80 can you please assign this issue to me.

**Comment by Nandini80** [comment]
Assigned.

**Comment by adarsh-site** [comment]
@Nandini80 I have created a pr, please check it let me know for any feedback.
