### ISSUE TITLE
Enhancement Requests for Certain Pages and Contact us section

### ISSUE THREAD

**Issue by adarsh-site** [Nandini80/Pill-Share#11]
certain pages could benefit from enhancements to improve user experience and provide more comprehensive information

<img width="941" alt="image" src="https://github.com/Nandini80/Pill-Share/assets/120160355/0e250e51-393d-4f01-bbe4-874cc97a655c">

**Comment by Nandini80** [comment]
Please complete the tasks that I have already assigned to you.
