### ISSUE TITLE
Security Threat : Exposed DB Configs

### ISSUE THREAD

**Issue by jiveshkalra** [Nandini80/Pill-Share#13]
The MYSQL DB Config username,password everything is given inside the project files .

**Comment by jiveshkalra** [comment]
bymistake closed the issue*

**Comment by jiveshkalra** [comment]
Uhmm , I just realised 
its not only the sqlDB credentials 
but even your gmail mail and passwords are exposed for some reason

**Comment by Nandini80** [comment]
Assigning this issue to you.
