### ISSUE TITLE
Signup is not working properly

### ISSUE THREAD

**Issue by Nandini80** [Nandini80/Pill-Share#15]

**Comment by jiveshkalra** [comment]
hey can you please assign this issue to me ?

**Comment by Nandini80** [comment]
Assigning this issue.

**Comment by Nandini80** [comment]
Any updates?

**Comment by jiveshkalra** [comment]
Yup working on it
though i got a bit busy with some other projects recently

and this one is a specially major issue 
probably i guess if i fix it 100% , my PR will be atleast 3k-4k lines code changed (idk exact,but it will be my biggest PR ever atleast)
cause i will have to rewrite entire system of login signup and all other forms and backend in a better manner
currently the project uses ajax ,sends credentials as GET req ~ big security threat, and also there is no proper session/token login system
adding all these will take a significant time

**Comment by Nandini80** [comment]
ok then attach a video of the working site with your PR.
