### ISSUE TITLE
Upgrading the UI of the site

### ISSUE THREAD

**Issue by alvin-dennis** [Nandini80/Pill-Share#24]
I wanted to upgrade the basic UI of the website as it looked basic and not well structured. @Nandini80 pls assign me this issue under PHICSIT. Including dark and light mode etc...
@Nandini80 Assign me?

**Comment by Nandini80** [comment]
I have already assigned this issue to you. You can start working on it.

**Comment by alvin-dennis** [comment]
@Nandini80 Apull request is created. pls check
