### ISSUE TITLE
Security Issue : The code is Prone to SQL Injections

### ISSUE THREAD

**Issue by jiveshkalra** [Nandini80/Pill-Share#26]
The Mysql queries are not secure and anyone can inject malicious code to the backend server

**Comment by Nandini80** [comment]
How will you resolve this issue?

**Comment by jiveshkalra** [comment]
just assign it to me and wait and watch 😏

**Comment by jiveshkalra** [comment]
Wait nevermind mb mb, I thought you have to use the  `connection.escape()` function to escape the strings and prevent the injections but with new updates of mysql its done internally so i guess there is no need for this change
