### ISSUE TITLE
Issue : "Eye" button does nothing

### ISSUE THREAD

**Issue by Sahil-Chhoker** [Nandini80/Pill-Share#3]
Issue : The "eye" button in e-mail field does nothing:

![image](https://github.com/Nandini80/Pill-Share/assets/155215308/fc9f50fd-a283-44cb-a0cc-c5ed4ff6b953)
 and 
![Screenshot 2024-03-10 151506](https://github.com/Nandini80/Pill-Share/assets/155215308/603de2aa-d0f4-490d-9be4-7d3d412c78fa)

Both are same!!!

**Comment by Nandini80** [comment]
Thanks for creating this issue.
How will you solve it? Please explain

**Comment by Sahil-Chhoker** [comment]
In which file exactly do you handle the sign up?

**Comment by Nandini80** [comment]
In index.html file

**Comment by Sahil-Chhoker** [comment]
I will try removing the icon from there.

**Comment by Nandini80** [comment]
but don't remove the person icon from there but change it so that it will not get clicked
<img width="101" alt="image" src="https://github.com/Nandini80/Pill-Share/assets/121488571/eb4ad34a-bfb1-4d29-bd56-a54da0339b10">

**Comment by Sahil-Chhoker** [comment]
ok
