### ISSUE TITLE
Security Threat: No login checks in admin panels

### ISSUE THREAD

**Issue by jiveshkalra** [Nandini80/Pill-Share#31]
anyone can access all the admin panels without logging in as admin, just by knowing the url anyone can get the access to the admin panels

**Comment by Nandini80** [comment]
What are the credentials for the admin panel?

**Comment by jiveshkalra** [comment]
Sent you on discord!

**Comment by Nandini80** [comment]
ok

**Comment by Nandini80** [comment]
@jiveshkalra Will you work on the issue that other buttons are not working in the hosted link of dashboard?
