### ISSUE TITLE
Host the project

### ISSUE THREAD

**Issue by Nandini80** [Nandini80/Pill-Share#34]

**Comment by jiveshkalra** [comment]
I think i can take it on, but to host it need to be added as a Collaborator in  the repository 
( ref on how to do that  - > [Click Here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository))

**Comment by Nandini80** [comment]
I don't think there is a need to do so

**Comment by jiveshkalra** [comment]
wait nevermind! mb

**Comment by jiveshkalra** [comment]
I mean I can host from my fork
but as soon as the phicsit opensource hackathon gets over, I wont be updating that fork and the website wont be updated on its on and will get outdated soon

**Comment by Nandini80** [comment]
Okay, we can do one thing. I'll add you as a contributor, and you can host the project. Afterward, I can remove you as a contributor if you're okay with that.

**Comment by jiveshkalra** [comment]
sure , we can try that out
(saying "try" cause i dont know the website will be updated even after I am not the collaborator)

**Comment by Nandini80** [comment]
ok lets give it a try

**Comment by Nandini80** [comment]
Added you as a contributor

**Comment by Nandini80** [comment]
Added you as a contributor

**Comment by Nandini80** [comment]
@jiveshkalra  Thanks for your contribution.
