### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by alvin-dennis** [Nandini80/Pill-Share#41]
Adding a loader page. @Nandini80 pls assign me this issue

**Comment by Nandini80** [comment]
ok but now make sure it is working correctly.

**Comment by alvin-dennis** [comment]
@Nandini80 yeah
 But ur file structure is difficult to understand

**Comment by alvin-dennis** [comment]
@Nandini80 we have made todi things for today and tmrw. I was jot able to contact u through whatsapp
