### ISSUE TITLE
Non-functional "Update" and "Save" Buttons in Profile Form

### ISSUE THREAD

**Issue by adarsh-site** [Nandini80/Pill-Share#8]
issue -  The "Update" and "Save" buttons seem to be non-functional

<img width="947" alt="image" src="https://github.com/Nandini80/Pill-Share/assets/120160355/5df60a18-2f75-4a41-9cc6-40cf32aada80">

**Comment by Nandini80** [comment]
These buttons are saving the data in the sql. They are working correctly.

**Comment by adarsh-site** [comment]
> These buttons are saving the data in the sql. They are working correctly.

I appreciate the response to the previous issue regarding the "Update" and "Save" buttons, confirming that they are saving data in the database. However, I'd like to bring up a user experience concern.

After pressing the "Update" or "Save" buttons in the profile form, there is no confirmation message indicating that the data has been successfully saved.
Users should receive a confirmation message or feedback after successfully updating or saving their profile information.

**Comment by Nandini80** [comment]
The issue you mentioned is significant. Therefore, I will assign this task to you, but please prioritize completing your other assigned tasks first.

**Comment by Nandini80** [comment]
Assigned.

**Comment by Nandini80** [comment]
@jinx-vi-0 Are you working on this issue?

**Comment by adarsh-site** [comment]
@Nandini80 Unfortunately, due to unforeseen circumstances, I won't be able to continue working on this issue. So, please assign it to someone else.
