### ISSUE TITLE
Make Certain Options Mandatory in Profile Form

### ISSUE THREAD

**Issue by adarsh-site** [Nandini80/Pill-Share#9]
certain fields should be mandatory to ensure users provide essential information

<img width="949" alt="image" src="https://github.com/Nandini80/Pill-Share/assets/120160355/68994e48-72ab-4165-a705-84e2389dafdd">

**Comment by Nandini80** [comment]
Thank you for bringing this issue. I am assigning it to you. Please keep me updated.
